#+title: iceberg-theme.el
#+author: Naoya Yamashita

[[https://github.com/conao3/iceberg-theme.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/iceberg-theme.el.png]]

[[https://github.com/conao3/iceberg-theme.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/iceberg-theme.el.svg?style=flat-square]]
[[https://github.com/conao3/iceberg-theme.el/releases][https://img.shields.io/github/tag/conao3/iceberg-theme.el.svg?style=flat-square]]
[[https://github.com/conao3/iceberg-theme.el/actions][https://github.com/conao3/iceberg-theme.el/workflows/Main%20workflow/badge.svg]]

A dark blue color theme for Emacs, designed to be easy on the eyes during long coding sessions.

This is an Emacs port of [[https://github.com/cocopon/iceberg.vim][iceberg.vim]] by [[https://github.com/cocopon][cocopon]].

[[https://github.com/conao3/iceberg-theme.el][https://raw.githubusercontent.com/conao3/files/master/blob/iceberg-theme.el/iceberg-theme.png]]

* Features

- Dark blue color palette optimized for readability
- Built on top of the solarized-theme framework
- Extensive face customizations for major modes
- Support for Markdown, Org mode, Haskell, PHP, and web development

* Requirements

- Emacs 28.1 or later
- [[https://github.com/bbatsov/solarized-emacs][solarized-theme]] 1.3 or later

* Installation

** Using leaf (recommended)

#+begin_src emacs-lisp
(leaf iceberg-theme
  :ensure t
  :config
  (iceberg-theme-create-theme-file)
  (load-theme 'solarized-iceberg-dark t))
#+end_src

** Using use-package

#+begin_src emacs-lisp
(use-package iceberg-theme
  :ensure t
  :config
  (iceberg-theme-create-theme-file)
  (load-theme 'solarized-iceberg-dark t))
#+end_src

** Manual installation

Clone this repository and add it to your load path:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/iceberg-theme.el")
(require 'iceberg-theme)
(iceberg-theme-create-theme-file)
(load-theme 'solarized-iceberg-dark t)
#+end_src

* Contributing

Contributions are welcome. Please feel free to open issues or submit pull requests.

** Development Setup

1. Install [[https://github.com/cask/cask][Cask]] for dependency management:

   #+begin_src shell
   # macOS
   brew install cask

   # Manual installation
   git clone https://github.com/cask/cask ~/.cask
   export PATH="$HOME/.cask/bin:$PATH"
   #+end_src

2. Clone the repository and install dependencies:

   #+begin_src shell
   git clone https://github.com/conao3/iceberg-theme.el
   cd iceberg-theme.el
   make
   #+end_src

** Testing

Run the test suite with:

#+begin_src shell
make test
#+end_src

* License

GPL-3.0. See [[https://github.com/conao3/iceberg-theme.el/blob/master/LICENSE][LICENSE]] for details.

Copyright (c) Naoya Yamashita

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
